### PR TITLE
Add blog post about ClojureScript and Servant

### PR DESCRIPTION
**Pull request by Jarzka**
Add blog post about ClojureScript and Servant

### CODE REVIEW

**Comment by Rinorragi** [comment]
Nice post! Quiclly went through it and didn't find much to be changed. You could add tags though.

**Comment by Jarzka** [comment]
Done.

**Comment by Rinorragi** [comment]
All categories will be added to the url and thus obfuscate the url a bit. I would not recommended using them unless you are sure about them. Some blogs are using them in integration purposes for extracting feed to another party.

**Comment by Jarzka** [comment]
Ok, I removed the categories

**Pull request merged**
