### PR TITLE
Post about active directory integration with Episerver

### PR DESCRIPTION
**Pull request by jukkahyv**

### CODE REVIEW

**Comment by Rinorragi** [comment]
You could add DOTNET to tags also. Not sure if "programming" tag is needed since I guess everything in this blog is about programming. Your call. :)

**Comment by Rinorragi** [comment]
In LDAP you need to use '** instead --> I guess you meant '*'

**Comment by Rinorragi** [comment]
I would like to have parameters of following line in separate rows (sideway scrollbars are annoying):  
public override MembershipUserCollection FindUsersByName(
  string usernameToMatch, 
  int pageIndex, 
  int pageSize, 
  out int totalRecords)

**Comment by Rinorragi** [comment]
where groupsToGet is a list of AD group names to be loaded.  --> Where

**Comment by Rinorragi** [comment]
Overall I felt that this was interesting and a fine post. Good job Jukka! :)

**Comment by Rinorragi** [comment]
Update also the date of the file for today merge :)

**Comment by jukkahyv** [comment]
That lowercase "where" was actually intentional since it was kind of supposed to be part of sentence, but you're right, it's better to change it to a whole sentence and start with a capital letter

**Pull request merged**
